### PR TITLE
C tag negative and positive tags 76X port

### PR DESCRIPTION
**Pull request by mverzett**
@imarches @kovitang can you have a look and see if I got anything wrong?

### CODE REVIEW

**Comment by ghost** [comment]
@mverzett thanks, I will have a look. Would you mind checking why with your commit "cherry-pick conflicts solved" all the setupBTagging part appears as new? You will want to use this branch for the cmssw PR and this would likely not be accepted, as it does not allow to track down clearly what you actually changed

**Comment by kovitang** [comment]
@mverzett  one comment on this file https://github.com/mverzett/cmssw/blob/CTag_NegativePositive_Tags76X/RecoBTag/CTagging/python/charmTaggerProducer_cfi.py
I needed these lines
https://github.com/kovitang/cmssw/blob/03ea65d867d6f56297c86e7643365a4a14e3b311/RecoBTag/CTagging/python/charmTaggerProducer_cfi.py#L5 
and 
https://github.com/kovitang/cmssw/blob/03ea65d867d6f56297c86e7643365a4a14e3b311/RecoBTag/CTagging/python/charmTaggerProducer_cfi.py#L9 
to get these work 
https://github.com/kovitang/cmssw/blob/03ea65d867d6f56297c86e7643365a4a14e3b311/RecoBTag/CTagging/python/charmTaggerProducer_cfi.py#L39-L40

**Comment by mverzett** [comment]
Hi @imarches ,

The reason why everything is marked as new is that everything there **is** new. There has been a refactoring between 7.6 and 8.0 of that part of code and this backport uses it. It is not strictly necessary for doing the job, but it was easier to update the whole file. Also, this is **not** the one planned to become the PR to the official repository, as it is for 7.6

**Comment by mverzett** [comment]
@kovitang, I'm looking into that.

**Comment by ghost** [comment]
@mverzett I see, you used an older version of 76X. Did you try cherry picking to an uptodate release, such as 765? This may be easier for you and things would be cleaner. The current recipe of the BTagAnalyzer is based on 763 just because so far there was no reason to move to 765, but it's a moment to update the recipe.

**Comment by mverzett** [comment]
I did it based on 763 because it was on the recipe :). I can try to rebase and see what happens but first I would like to complete the 80x PR

@kovitang , indeed there was a problem. Now I fixed it. The reason it needs such fix is that the computer configuration is stored under the slComputerCfg PSet, as it was done before the changes were not used.

**Pull request closed without merging**
